//
//  SplashScreenWireframe.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class SplashScreenWireframe: BaseWireframe {

  // MARK: - Module setup

  static func configureModule() -> UIViewController {
    let viewController = SplashScreenViewController()
    let wireframe = SplashScreenWireframe(viewController: viewController)
    let interactor = SplashScreenInteractor()
    let presenter = SplashScreenPresenter(wireframe: wireframe, view: viewController, interactor: interactor)
    
    viewController.presenter = presenter
    
    return viewController
  }
    
  // MARK: - Private Routing

}

// MARK: - Extensions

extension SplashScreenWireframe: SplashScreenWireframeInterface {
  func navigate(to option: SplashScreenNavigationOption) {
    // switch option {
    // case <#pattern#>:
    //   <#code#>      
    // }
  }
}
