//
//  SplashScreenViewController.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class SplashScreenViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var titleLabel: UILabel!
    
    // MARK: - Class properties
    
    // MARK: - Public properties
    
    var presenter: SplashScreenPresenterInterface!
    
    // MARK: - Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.viewConfiguration()
    }
    
    // MARK: - Class Configurations
    private func viewConfiguration() {
        presenter.startSplashAnimation(titleLabel)
    }
    
    // MARK: - UIActions
    
    // MARK: - Class Methods
    
}

// MARK: - Extensions
extension SplashScreenViewController: SplashScreenViewInterface { }
