//
//  FavoritesScreenWireframe.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class FavoritesScreenWireframe: BaseWireframe {

  // MARK: - Module setup

  static func configureModule() -> UIViewController {
    let viewController = FavoritesScreenViewController()
    let wireframe = FavoritesScreenWireframe(viewController: viewController)
    let interactor = FavoritesScreenInteractor()
    let presenter = FavoritesScreenPresenter(wireframe: wireframe, view: viewController, interactor: interactor)
    
    viewController.presenter = presenter
    
    return viewController
  }
    
  // MARK: - Private Routing
    private func goToDetail(_ favoriteMovie: FavoriteMovie?) {
        let viewController = MovieDetailsWireframe.configureModule(contentID: 0, favoriteData: true, favoriteMovie: favoriteMovie)
        self.present(viewController, animated: true)
    }

}

// MARK: - Extensions

extension FavoritesScreenWireframe: FavoritesScreenWireframeInterface {
  func navigate(to option: FavoritesScreenNavigationOption) {
     switch option {
     case .goToMovieDetail(let favoriteMovie):
       goToDetail(favoriteMovie)
     }
  }
}
