//
//  FavoritesScreenWireframe.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class FavoritesScreenWireframe: BaseWireframe {

  // MARK: - Module setup

  static func configureModule() -> UIViewController {
    let viewController = FavoritesScreenViewController()
    let wireframe = FavoritesScreenWireframe(viewController: viewController)
    let interactor = FavoritesScreenInteractor()
    let presenter = FavoritesScreenPresenter(wireframe: wireframe, view: viewController, interactor: interactor)
    
    viewController.presenter = presenter
    
    return viewController
  }
    
  // MARK: - Private Routing

}

// MARK: - Extensions

extension FavoritesScreenWireframe: FavoritesScreenWireframeInterface {
  func navigate(to option: FavoritesScreenNavigationOption) {
    // switch option {
    // case <#pattern#>:
    //   <#code#>      
    // }
  }
}
