//
//  FavoritesScreenInterfaces.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

enum FavoritesScreenNavigationOption { }

protocol FavoritesScreenWireframeInterface: WireframeInterface {
    func navigate(to option: FavoritesScreenNavigationOption)
}

protocol FavoritesScreenViewInterface: ViewInterface { }

protocol FavoritesScreenPresenterInterface: PresenterInterface {
    func setupFavoritesHeader(_ title: UILabel, _ icon: UIImageView)
    func configure(_ collectionView: UICollectionView)
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath)
    func numberOfItemsInSection(_ collectionView: UICollectionView, section: Int) -> Int
    func cellForItemAt(_ collectionView: UICollectionView, indexPath: IndexPath) -> UICollectionViewCell
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize 
}

protocol FavoritesScreenInteractorProtocol: InteractorInterface { }
