//
//  FavoritesScreenPresenter.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class FavoritesScreenPresenter {
    
    // MARK: - Private properties
    
    private weak var view: FavoritesScreenViewInterface?
    private let interactor: FavoritesScreenInteractorProtocol
    private let wireframe: FavoritesScreenWireframeInterface
        
    private enum Strings {
        static let title = ""
    }
    
    // MARK: - Lifecycle
    
    init(wireframe: FavoritesScreenWireframeInterface, view: FavoritesScreenViewInterface, interactor: FavoritesScreenInteractorProtocol) {
        self.wireframe = wireframe
        self.view = view
        self.interactor = interactor
    }
}

// MARK: - Extensions

extension FavoritesScreenPresenter: FavoritesScreenPresenterInterface { }
