//
//  FavoritesScreenInterfaces.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

enum FavoritesScreenNavigationOption { }

protocol FavoritesScreenWireframeInterface: WireframeInterface {
    func navigate(to option: FavoritesScreenNavigationOption)
}

protocol FavoritesScreenViewInterface: ViewInterface { }

protocol FavoritesScreenPresenterInterface: PresenterInterface { }

protocol FavoritesScreenInteractorProtocol: InteractorInterface { }
