//
//  MovieDetailsPresenter.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class MovieDetailsPresenter {
    
    // MARK: - Private properties
    private weak var view: MovieDetailsViewInterface?
    private let interactor: MovieDetailsInteractorProtocol
    private let wireframe: MovieDetailsWireframeInterface
        
    private enum Strings {
        static let releaseDateTitle = MovieDetailsViewControllerStrings.releaseDateTitle.localized()
        static let runtimeTitle = MovieDetailsViewControllerStrings.runtimeTitle.localized()
        static let descriptionTitleLable = MovieDetailsViewControllerStrings.descriptionTitleLable.localized()
        static let watchNowButton = MovieDetailsViewControllerStrings.watchNowButton.localized()
        static let warningRedirectExternalLink = MovieDetailsViewControllerStrings.warningRedirectExternalLink.localized()
        static let theMovieDbCredits = MovieDetailsViewControllerStrings.theMovieDbCredits.localized()
    }
    
    private enum Constants {
        static let iPhoneBaseScrollViewHeight = 800
        static let iPadBaseScrollViewHeight = 1000
        static let baseLabelLineHeight = 17
    }
    
    private var movieDetails: MovieDetails? {
        didSet {
            guard let movieDetails = movieDetails else { return }
            checkIfRequestIsDone()
            view?.loadInformations(movie: movieDetails)
        }
    }
    
    private var movieGenresList: GenresList? {
        didSet {
            checkIfRequestIsDone()
        }
    }
    
    private var movieVideos: MovieVideo? {
        didSet {
            view?.getVideoId(getTrailerVideoId(movieVideos))
        }
    }
    
    private var favoriteData: Bool
    
    // MARK: - Lifecycle
    init(wireframe: MovieDetailsWireframeInterface, view: MovieDetailsViewInterface, interactor: MovieDetailsInteractorProtocol, favoriteData: Bool) {
        self.wireframe = wireframe
        self.view = view
        self.interactor = interactor
        self.favoriteData = favoriteData
    }
    
    func viewDidLoad() {
        loadLanguage()
        makeRequests()
    }
    
    private func makeRequests() {
        view?.showLoading(hide: false)
        if !favoriteData {
            interactor.getMovieDetails()
            interactor.getMovieGenres()
            interactor.getMovieVideos()
        }
    }
    
    private func loadFavoriteData() {
        
    }
    
    private func loadLanguage() {
        view?.loadLanguage(releaseDate: Strings.releaseDateTitle,
                           runtime: Strings.runtimeTitle,
                           description: Strings.descriptionTitleLable,
                           watchNow: Strings.watchNowButton,
                           warningExternalLinks: Strings.warningRedirectExternalLink,
                           theMovieDbCredits: Strings.theMovieDbCredits)
    }
    
    private func getTrailerVideoId(_ movieVideo: MovieVideo?) -> String {
        guard let movieVideo = movieVideo, let Id = movieVideo.results.first?.key else { return "" }
        return Id
    }
    
    private func checkIfRequestIsDone() {
        if let movieDetails = movieDetails, movieGenresList != nil {
            view?.loadGenres(getGenreName(movieDetails.genres))
            view?.showLoading(hide: true)
        }
    }
    
    private func checkIfItIsFavorited() -> Bool {
        if let favoritesMovies = UserDefaults.standard.getMovieDetailsObject() {
            let currentModel = FavoriteMovie(movieDetails: movieDetails, movieVideo: movieVideos, movieGenres: movieGenresList)
            let validator = favoritesMovies.contains { (favorite) in
                favorite == currentModel
            }
            return validator
        } else {
            return false
        }
    }
    
    private func getGenreName(_ genres: [Genre]?) -> [String] {
        guard let genres = genres else { return [""] }
        var formattedGenre: [String] = []
        var validator: Bool?
        var i = 0
        for id in genres {
            validator = self.movieGenresList?.genres.contains(where: { genre in
                if genre.id == id.id, let name = genre.name {
                    formattedGenre.append(name)
                    return true
                } else {
                    return false
                }
            })
            
            i += 1
        }
        
        if validator ?? false {
            return formattedGenre
        } else {
            return [""]
        }
    }
}

// MARK: - Extensions
extension MovieDetailsPresenter: MovieDetailsPresenterInterface {
    func checkIfItsFavorited(_ button: UIButton) {
        view?.updateFavoriteButton(isFavorited: checkIfItIsFavorited())
    }
    
    func saveToFavorites() {
        let object = FavoriteMovie(movieDetails: movieDetails, movieVideo: movieVideos, movieGenres: movieGenresList)
        if checkIfItIsFavorited() {
            UserDefaults.standard.removeMovieDetailsObject(object)
        } else {
            UserDefaults.standard.saveMovie([object])
        }
        view?.updateFavoriteButton(isFavorited: checkIfItIsFavorited())
    }
    
    func updateScrollViewHeight(_ label: UILabel, _ constraint: NSLayoutConstraint) {
        let descriptionLabelSize = label.numberOfVisibleLines
        let baseHeight = UIDevice.current.userInterfaceIdiom == .phone ? Constants.iPhoneBaseScrollViewHeight : Constants.iPadBaseScrollViewHeight
        constraint.constant = CGFloat(baseHeight + (descriptionLabelSize * Constants.baseLabelLineHeight))
    }
    
    func animateScreenWhenScrool(_ isScrolling: Bool, _ constraint: NSLayoutConstraint) {
        let constraintWhenIsScrolling: CGFloat = -100
        let constraintWhenIsNotScrolling: CGFloat = 0
        
        if isScrolling {
            constraint.constant = constraintWhenIsScrolling
        } else {
            constraint.constant = constraintWhenIsNotScrolling
        }
        
        UIView.animate(withDuration: 0.3) {
            self.view?.layoutIfNeeded()
        }
    }
    
    func getWatchNowLink() -> String {
        return EndPoint.watchNowLink(contentID: movieDetails?.id ?? 0).fullPath
    }
}

extension MovieDetailsPresenter: MovieDetailsInteractorResponseProtocol {
    func responseGetMovieVideos(movieVideos: MovieVideo?) {
        self.movieVideos = movieVideos
    }
    
    func responseGetMovieGenres(genres: GenresList?) {
        self.movieGenresList = genres
    }
    
    func responseGetMovieDetailsSuccess(movie: MovieDetails?) {
        self.movieDetails = movie
    }
    
    func responseGetMovieDetailsError() {
        //TODO
    }
    
    func networkingNotAvailable() {
        //TODO
    }
}
