//
//  MovieDetailsInterfaces.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

enum MovieDetailsNavigationOption { }

protocol MovieDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: MovieDetailsNavigationOption)
}

protocol MovieDetailsViewInterface: ViewInterface {
    func layoutIfNeeded()
    func showLoading(hide: Bool)
    func loadGenres(_ genres: [String])
    func loadInformations(movie: MovieDetails)
    func getVideoId(_ videoId: String)
    func loadLanguage(releaseDate: String, runtime: String, description: String, watchNow: String, warningExternalLinks: String, theMovieDbCredits: String)
}

protocol MovieDetailsPresenterInterface: PresenterInterface {
    func getWatchNowLink() -> String
    func animateScreenWhenScrool(_ isScrolling: Bool, _ constraint: NSLayoutConstraint)
    func updateScrollViewHeight(_ label: UILabel, _ constraint: NSLayoutConstraint)
}

protocol MovieDetailsInteractorProtocol: InteractorInterface {
    func getMovieDetails()
    func getMovieGenres()
    func getMovieVideos()
}
