//
//  HomeScreenInteractor.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//
//

import Foundation

final class HomeScreenInteractor {
}

// MARK: - Extensions

extension HomeScreenInteractor: HomeScreenInteractorProtocol {
}

extension HomeScreenInteractor: NetworkInteractorResponse {
  func networkingAvailable(_ ID: NetworkResponseType) {
    
  }
  
  func networkingNotAvailable(_ ID: NetworkResponseType) {

  }
}
