//
//  HomeScreenPresenter.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class HomeScreenPresenter {
    
    // MARK: - Private properties
    
    private weak var view: HomeScreenViewInterface?
    private let interactor: HomeScreenInteractorProtocol
    private let wireframe: HomeScreenWireframeInterface
        
    private enum Strings {
        static let title = ""
    }
    
    // MARK: - Lifecycle
    
    init(wireframe: HomeScreenWireframeInterface, view: HomeScreenViewInterface, interactor: HomeScreenInteractorProtocol) {
        self.wireframe = wireframe
        self.view = view
        self.interactor = interactor
    }
    
    func viewDidLoad() {
        interactor.getPopularMovies()
    }
}

// MARK: - Presenter Extension
extension HomeScreenPresenter: HomeScreenPresenterInterface { }

// MARK: - Interactor Extension
extension HomeScreenPresenter: HomeScreenInteractorResponseProtocol {
    func responseGetPopularMoviesSuccess(movie: Movie?) {
        print(movie)
    }
    
    func responseGetPopularMoviesError() {
        print("Error")
    }
    
    func networkingNotAvailable() {
        print("Networking not available")
    }
    
}
