//
//  HomeScreenViewController.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class HomeScreenViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var welcomeLabel: UILabel!
    @IBOutlet weak var subtitleLabel: UILabel!
    @IBOutlet weak var icon: UIImageView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    // MARK: - Class properties
    
    // MARK: - Public properties
    var presenter: HomeScreenPresenterInterface!
    
    // MARK: - Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        self.viewConfiguration()
    }
    
    // MARK: - Class Configurations
    private func viewConfiguration() {
        presenter.configure(collectionView)
        
        collectionView.delegate = self
        collectionView.dataSource = self
        
        presenter.setupWelcomeHeader(welcomeLabel, subtitleLabel, icon)
    }
    
    // MARK: - UIActions
    
    // MARK: - Class Methods
    
}

// MARK: - Extensions
extension HomeScreenViewController: HomeScreenViewInterface {
    func showLoading(hide: Bool) {
        
    }
    
    func reloadData() {
        self.collectionView.reloadData()
    }
}

// MARK: - CollectionView Exension
extension HomeScreenViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return presenter.numberOfItemsInSection(collectionView, section: section)
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        return self.presenter.cellForItemAt(collectionView, indexPath: indexPath)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.presenter.collectionView(collectionView, didSelectItemAt: indexPath)
    }
}
