//
//  HomeScreenViewController.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class HomeScreenViewController: UIViewController {
    
    // MARK: - Outlets
    
    // MARK: - Class properties
    
    // MARK: - Public properties
    
    var presenter: HomeScreenPresenterInterface!
    
    // MARK: - Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.viewConfiguration()
        presenter.viewDidLoad()
    }
    
    // MARK: - Class Configurations
    
    private func viewConfiguration() { }
    
    // MARK: - UIActions
    
    // MARK: - Class Methods
    
}

// MARK: - Extensions

extension HomeScreenViewController: HomeScreenViewInterface { }
