//
//  HomeScreenInterfaces.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

enum HomeScreenNavigationOption { }

protocol HomeScreenWireframeInterface: WireframeInterface {
    func navigate(to option: HomeScreenNavigationOption)
}

protocol HomeScreenViewInterface: ViewInterface { }

protocol HomeScreenPresenterInterface: PresenterInterface {
    func setupWelcomeHeader(_ title: UILabel, _ subtitle: UILabel, _ icon: UIImageView)
}

protocol HomeScreenInteractorProtocol: InteractorInterface {
    func getPopularMovies()
}
