//
//  HomeScreenViewController.swift
//  VeryCreatives
//
//  Created by Brenner on 06/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class HomeScreenViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var welcomeLabel: UILabel!
    @IBOutlet weak var subtitleLabel: UILabel!
    @IBOutlet weak var icon: UIImageView!
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var optionsSegmentedControl: UISegmentedControl!
    
    // MARK: - Class properties
    
    // MARK: - Public properties
    var presenter: HomeScreenPresenterInterface!
    
    // MARK: - Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        self.viewConfiguration()
    }
    
    // MARK: - Class Configurations
    private func viewConfiguration() {
        presenter.configure(collectionView)
        
        collectionView.delegate = self
        collectionView.dataSource = self
        
        presenter.setupWelcomeHeader(welcomeLabel, subtitleLabel, icon)
        presenter.setupSegmentedControl(optionsSegmentedControl)
    }
    
    // MARK: - UIActions
    @IBAction func sortMovies(_ sender: UISegmentedControl) {
        let validator = sender.selectedSegmentIndex == 0 ? true : false
        presenter.sortMovies(isPopularMovies: validator)
    }

    // MARK: - Class Methods
    
}

// MARK: - Extensions
extension HomeScreenViewController: HomeScreenViewInterface {
    func showLoading(hide: Bool) {
        self.fullScreenLoading(hide: hide)
    }
    
    func reloadData() {
        self.collectionView.reloadData()
    }
}

// MARK: - CollectionView Exension
extension HomeScreenViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return presenter.numberOfItemsInSection(collectionView, section: section)
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        return presenter.cellForItemAt(collectionView, indexPath: indexPath)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        presenter.collectionView(collectionView, didSelectItemAt: indexPath)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return presenter.collectionView(collectionView, layout: collectionViewLayout, sizeForItemAt: indexPath)
    }
}
