//
//  MovieDetailInterfaces.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

enum MovieDetailNavigationOption { }

protocol MovieDetailWireframeInterface: WireframeInterface {
    func navigate(to option: MovieDetailNavigationOption)
}

protocol MovieDetailViewInterface: ViewInterface {
    func layoutIfNeeded()
    func showLoading(hide: Bool)
    func loadGenres(_ genres: [String])
    func loadInformations(movie: MovieDetail)
    func getVideoId(_ videoId: String)
    func loadLanguage(releaseDate: String, runtime: String, description: String, watchNow: String, warningExternalLinks: String, theMovieDbCredits: String)
}

protocol MovieDetailPresenterInterface: PresenterInterface {
    func getWatchNowLink() -> String
    func animateScreenWhenScrool(_ isScrolling: Bool, _ constraint: NSLayoutConstraint)
    func updateScrollViewHeight(_ label: UILabel, _ constraint: NSLayoutConstraint)
}

protocol MovieDetailInteractorProtocol: InteractorInterface { }
