//
//  MovieDetailInteractor.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//
//

import Foundation

final class MovieDetailInteractor {
}

// MARK: - Extensions

extension MovieDetailInteractor: MovieDetailInteractorProtocol {
}

extension MovieDetailInteractor: NetworkInteractorResponse {
  func networkingAvailable(_ ID: NetworkResponseType) {
    
  }
  
  func networkingNotAvailable(_ ID: NetworkResponseType) {

  }
}
