//
//  MovieDetailWireframe.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class MovieDetailWireframe: BaseWireframe {

  // MARK: - Module setup

  static func configureModule(contentID: Int) -> UIViewController {
    let viewController = MovieDetailViewController()
    let wireframe = MovieDetailWireframe(viewController: viewController)
    let interactor = MovieDetailInteractor()
    let presenter = MovieDetailPresenter(wireframe: wireframe, view: viewController, interactor: interactor)
    
    viewController.presenter = presenter
    
    return viewController
  }
    
  // MARK: - Private Routing

}

// MARK: - Extensions

extension MovieDetailWireframe: MovieDetailWireframeInterface {
  func navigate(to option: MovieDetailNavigationOption) {
    // switch option {
    // case <#pattern#>:
    //   <#code#>      
    // }
  }
}
