//
//  MovieDetailViewController.swift
//  VeryCreatives
//
//  Created by Brenner on 07/09/21.
//
//  This file was generated by the 💚 VIPER generator.
//

import UIKit

final class MovieDetailViewController: UIViewController {
    
    // MARK: - Outlets
    
    // Labels
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var votingRate: UILabel!
    @IBOutlet weak var releaseDateTitle: UILabel!
    @IBOutlet weak var runtimeTitle: UILabel!
    @IBOutlet weak var releaseDate: UILabel!
    @IBOutlet weak var runtime: UILabel!
    @IBOutlet weak var descriptionTitleLable: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var watchNowButton: UIButton!
    @IBOutlet weak var warningRedirectExternalLink: UILabel!
    @IBOutlet weak var theMovieDbCredits: UILabel!
    
    // Collections
    @IBOutlet var starsImageView: [UIImageView]!
    @IBOutlet var genresLabel: [UILabel]!
    
    // UIView
   // @IBOutlet weak var videoPlayer: YTPlayerView!
    @IBOutlet weak var contentView: UIView!
    @IBOutlet weak var coverImage: UIImageView!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var maskImageView: UIImageView!
    
    // MARK: - Constraints
    @IBOutlet weak var imageTopConstraint: NSLayoutConstraint!
    @IBOutlet weak var scrollViewHeight: NSLayoutConstraint!
    
    // MARK: - Class properties
    private var isScrolling = false {
        didSet {
            presenter.animateScreenWhenScrool(isScrolling, imageTopConstraint)
        }
    }
    
    private var watchNowLink: String?
        
    // MARK: - Public properties
    var presenter: MovieDetailPresenterInterface!
    
    // MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        self.viewConfiguration()
    }
    
    // MARK: - Class Configurations
    private func viewConfiguration() {
        maskImageView.applyGradient()
        scrollView.delegate = self
    }
    
    // MARK: - UIActions
    @IBAction func closeAction(_ sender: UIButton) {
        self.dismiss(animated: true, completion: nil)
    }
    
    @IBAction func scrollToTop(_ sender: UITapGestureRecognizer) {
        scrollView.setContentOffset(.zero, animated: true)
    }
    
    @IBAction func watchNowAction(_ sender: UIButton) {
        openExternalLinks(link: presenter.getWatchNowLink())
    }
    
    
    // MARK: - Class Methods
    
}

// MARK: - Extensions
extension MovieDetailViewController: MovieDetailViewInterface {
    func layoutIfNeeded() {
        self.view?.layoutIfNeeded()
    }
}

extension MovieDetailViewController: UIScrollViewDelegate {
    func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
        isScrolling = true
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        var position: [CGPoint] = []
        let scrollTop = CGPoint(x: 0.0, y: 0.0)
        let scrollOffset = scrollView.contentOffset
        
        position.append(scrollOffset)
        
        if position.count > 4 { position = [] }
        
        if position.first == scrollTop && position.last == scrollTop {
            isScrolling = false
        }
    }
}
